name: artifact testing

on:
    push:
    # pull_request:
    workflow_dispatch:

jobs:
    uploadjob:
        runs-on: ubuntu-latest
        env:
            INSTANCE1: art1
            INSTANCE2: art2
        steps:
        - name: create some files
          run: |
            pwd
            mkdir ronan
            cd ronan
            date >> ${{ env.INSTANCE1}}
            sleep 1
            date >> ${{ env.INSTANCE2}}
            pwd
            ls
        - name: upload ${{ env.INSTANCE2 }}
          uses: actions/upload-artifact@v3
          with:
            name: ${{ env.INSTANCE2 }}
            path: ${{ github.workspace }}
        
        - name: upload ${{ env.INSTANCE1 }}
          uses: actions/upload-artifact@v3
          with:
            name: ${{ env.INSTANCE1 }}
            path: ${{ github.workspace }}

        - name: cache those files
          uses: actions/cache@v3
          with:
            path: ${{ github.workspace }}
            key: synnott
            
    downloadjob:
        needs: uploadjob
        runs-on: ubuntu-latest
        env:
            INSTANCE1: art1
            INSTANCE2: art2
        steps:
        - name: testing123
          run: |
            pwd
            ls
            cat ${{ env.INSTANCE1}}
            cat ${{ env.INSTANCE2}}
