name: artifact testing

on:
    push:
    # pull_request:
    workflow_dispatch:

jobs:
    uploadjob:
        runs-on: ubuntu-latest
        env:
            INSTANCE1: artifact1
            INSTANCE2: artifact2
        steps:
        - name: create some files
          run: |
            pwd
            rm -rf ronan
            # mkdir dave
            # cd dave
            date >> ${{ env.INSTANCE1}}
            sleep 1
            date >> ${{ env.INSTANCE2}}
            pwd
            ls
        # - name: upload ${{ env.INSTANCE2 }}
          # uses: actions/upload-artifact@v3
          # with:
            # name: ${{ env.INSTANCE2 }}
            # path: ${{ github.workspace }}
        
        # - name: upload ${{ env.INSTANCE1 }}
          # uses: actions/upload-artifact@v3
          # with:
            # name: ${{ env.INSTANCE1 }}
            # path: ${{ github.workspace }}

        - name: cache ${{ env.INSTANCE1 }}
          uses: actions/cache@v3
          with:
            path: ${{ github.workspace }}
            key: ${{ env.INSTANCE1}}

        - name: cache ${{ env.INSTANCE2 }}
          uses: actions/cache@v3
          with:
            path: ${{ github.workspace }}
            key: ${{ env.INSTANCE2}}

    downloadjob:
        needs: uploadjob
        runs-on: ubuntu-latest
        env:
            INSTANCE1: artifact1
            INSTANCE2: artifact2
        steps:
        - name: cache ${{ env.INSTANCE1 }}
          uses: actions/cache@v3
          with:
            path: ${{ github.workspace }}
            key: ${{ env.INSTANCE1}}

        - name: cache ${{ env.INSTANCE2 }}
          uses: actions/cache@v3
          with:
            path: ${{ github.workspace }}
            key: ${{ env.INSTANCE2}}
        - name: testing123
          run: |
            pwd
            ls
            cat ${{ env.INSTANCE1}}
            cat ${{ env.INSTANCE2}}
