name: artifact testing

on:
    push:
    # pull_request:
    workflow_dispatch:

jobs:
    uploadjob:
        runs-on: ubuntu-latest
        env:
            INSTANCE1: artifact1.txt
            INSTANCE2: artifact2.txt
        steps:
        - name: create some files
          run: |
            pwd
            date >> ${{ env.INSTANCE1}}
            sleep 1
            date >> ${{ env.INSTANCE2}}
            pwd
            ls

        - name: upload ${{ env.INSTANCE2 }}
          uses: actions/upload-artifact@v3
          with:
            name: ${{ env.INSTANCE2 }}
            path: ${{ github.workspace }}/${{ env.INSTANCE2 }}
        
        - name: upload ${{ env.INSTANCE1 }}
          uses: actions/upload-artifact@v3
          with:
            name: ${{ env.INSTANCE1 }}
            path: ${{ github.workspace }}/${{ env.INSTANCE1 }}



    downloadjob:
        needs: uploadjob
        runs-on: ubuntu-latest
        env:
            INSTANCE1: artifact1.txt
            INSTANCE2: artifact2.txt
        steps:
        - name: Download artifact ${{ env.INSTANCE1 }}
          uses: actions/upload-artifact@v3
          with:
            name: ${{ env.INSTANCE1 }}
            path: ${{ github.workspace }}

        - name: Download artifact ${{ env.INSTANCE2 }}
          uses: dawidd6/action-download-artifact@v2
          with:
            name: ${{ env.INSTANCE2 }}
            path: ${{ github.workspace }}
         
        - name: test
          run: ls -R       


        - name: testing123
          run: |
            pwd
            ls
            cat ${{ env.INSTANCE1}}
            cat ${{ env.INSTANCE2}}
