name: artifact testing

jobs:
    upload:
        runs-on: ubuntu-latest
        env:
            INSTANCE1: art1
            INSTANCE2: art2
        steps:
        - name: create some files
          run: |
            pwd
            mkdir ronan
            cd ronan
            date >> ${{ env.INSTANCE1}}
            who >> ${{ env.INSTANCE2}}
            pwd
            ls
        - name: upload ${{ env.INSTANCE2 }}
          uses: actions/upload-artifact@v3
          with:
            name: ${{ env.INSTANCE2 }}
            path: ${{ github.workspace }}
        
        - name: upload ${{ env.INSTANCE1 }}
          uses: actions/upload-artifact@v3
          with:
            name: ${{ env.INSTANCE1 }}
            path: ${{ github.workspace }}
