# example workflow to control Arm Virtual Hardware

name: AVH_RPi4_Matter

# Controls when the workflow will run
on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_lighting_app:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Navigate to install dir and pull latest
        run: |
          cd /home/pi/connectedhomeip/examples/lighting-app/linux
          git pull
          
      - name: Rebuild lighting-app
        run: |
          gn gen out/debug
          ninja -C out/debug

  run_lighting_app:
    needs: build_lighting_app
    runs-on: self-hosted
    steps:
      - name: Run lighting-app for 60 seconds
        run: |
          cd /home/pi/connectedhomeip/examples/lighting-app/linux
          timeout 60s ./out/debug/chip-lighting-app
